### ISSUE TITLE
"like" posts require a title

### ISSUE THREAD

**Issue by cweiske** [snarfed/wordpress-micropub#41] opened 2016-09-14 06:40 UTC
When #40 is fixed you will see that sending a "like" request will fail unless the `name` property is also given.

Submitting likes via micropub should not require a title.

**Comment by snarfed** [comment] 2016-09-27 20:21
hey @cweiske, it looks like this might be fixed now. mind trying again?

**Comment by cweiske** [comment] 2016-09-28 04:16
I'm doing something wrong, or it's too early:

```
curl -i -X POST -H 'User-Agent: shpub' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Authorization: Bearer abc' -d 'h=entry' -d 'like-of=http://www.bogo' 'http://wordpress.bogo/?micropub=endpoint'

HTTP/1.1 500 Internal Server Error
Date: Wed, 28 Sep 2016 04:15:51 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.19
Link: <http://wordpress.bogo/?micropub=endpoint>; rel="micropub"
Link: <http://anoweco.bogo/auth.php>; rel="authorization_endpoint"
Link: <http://anoweco.bogo/token.php>; rel="token_endpoint"
Content-Length: 38
Connection: close
Content-Type: text/plain; charset=UTF-8

Content, title, and excerpt are empty.
```

**Comment by snarfed** [comment] 2016-09-29 05:55
heh, thanks for keeping me honest. adding `h=entry` to your query might fix it, but I'll reproduce myself.

do you know a way to set up shpub to work with a WordPress on localhost? indieauth obviously can't sign into localhost. maybe i can add it to the config manually?

**Comment by cweiske** [comment] 2016-09-29 05:58
In `~/.config/shpub.ini` add a section like this:

```
[wordpress]
server=http://wordpress.local
user=https://wordpress.local/user/3
token=asdf
```

**Comment by cweiske** [comment] 2016-09-29 18:36
I've got a local instance of anoweco running (commentpara.de, https://github.com/cweiske/anoweco) which you can configure as auth+token server in wordpress. This is probably the most easy way to get a token.

**Comment by snarfed** [comment] 2016-09-29 18:50
thanks! the wordpress plugin actually skips verifying tokens when it's running locally, though, so no need.

**Closed** 2016-09-30 05:20 UTC
