### ISSUE TITLE
support the syndication property

### ISSUE THREAD

**Issue by davidmead** [snarfed/wordpress-micropub#21] opened 2015-12-09 21:28 UTC
Hi @snarfed. Hope you can help.

I'm not getting the `'syndicate'` URL passed from photos posted on Instagram. I think I've tracked it down to this plugin. Brid.gy and OwnYourGram all seem to be doing what they should, but I cannot see in the plugin code, or resulting HTML of the WP post, the link back to the gram.

You can see an example at http://davidjohnmead.com/blog/2015/12/08/2864/.

Any ideas?

**Comment by snarfed** [comment] 2015-12-09 22:12
hey, thanks for filing! sorry, you're right, this plugin doesn't currently support syndication URLs, so that's currently the expected behavior. it's a great feature request though!

cc @dshanske, he's often interested in adding features like this.

**Comment by snarfed** [comment] 2015-12-09 22:13
in the micropub spec: http://micropub.net/#adding-a-syndication-url

**Comment by davidmead** [comment] 2015-12-11 03:42
Thanks @snarfed. I'm at a loss with editing the WP plugins, otherwise I'd have a go myself. Since moving over from Known, I'm noticing the WP Indieweb plugins don't seem to work together that much. Seems to be a few gaps not bridged in the whole posting/syndicating flow.

**Comment by dshanske** [comment] 2015-12-11 03:56
@davidmead I think we could do better at the flow. But remember that they aren't all written by the same people. @snarfed wrote the Micropub plugin. I wrote the Syndication Links and Post Kinds plugins @pfefferle wrote the Webmention and Semantic Linkbacks plugins. And while we've contributed to each other's work and talked...we haven't, although we probably should, worked together to a common vision. 

That said, Syndication Links does support syndication as a property and will display it if set by the Micropub plugin as a property(mf2_syndication). What is broken is support for adding a property after the fact, which is not included.

**Comment by davidmead** [comment] 2015-12-11 04:04
Don't get me wrong @dshanske. I appreciate the work you have all put in, and I use each of those plugins :-)

What I may do is quickly map _my_ process and expectations. I could be missing something, or highlight something that could tie some of these together :-)

**Comment by dshanske** [comment] 2015-12-11 04:10
I'm agreeing with you. Even my own plugins need to be clearer as to process. We don't just need programmers(of which I am not the best, admittedly). We need people to blog on how they set it up, to file issues, give input. 

If I was the only one giving feedback on what I did, I'd never put in clearer processes or better documentation because I know how it is supposed to work. Keep giving feedback.

**Comment by davidmead** [comment] 2015-12-11 04:11
:-)

Will do

**Comment by dshanske** [comment] 2015-12-11 04:12
Re @snarfed's comment about me adding the feature, the missing feature is adding properties after the fact, which the plugin doesn't support. But when the plugin started, the properties part was still in flux in the specification. It will support it eventually.

**Comment by davidmead** [comment] 2015-12-11 04:23
I get that. I used WP for sometime and had those in place. Past year or so I've been using Known, and there's been so much growth with what we can do with the Indieweb now. Most of that stuff was still not formed back then.  Downside to being on the cutting edge ;-)

**Comment by Ruxton** [comment] 2016-05-16 05:53
It's worth pointing out current master (0.4) looks to loosely supports this (by parsing all $_POST vars to mf2_$key) while the version of wordpress.org (0.3) does not (it has a whitelist of acceptable mf2 keys to convert from $_POST)

**Comment by snarfed** [comment] 2016-05-16 16:12
@Ruxton good point! thanks for the nudge. i've pushed current master (0.4) to wordpress.org: https://wordpress.org/plugins/micropub/

sounds like that doesn't fully implement the syndication property, though, so i'll leave this issue open. @dshanske @davidmead feel free to weigh in.

**Comment by Ruxton** [comment] 2016-05-17 00:41
Along with syndicated links plugin, things behave properly (as I'd expect anyway) on the home page but not on single post pages.  First few posts on my site show it https://ignite.digitalignition.net/

**Comment by snarfed** [comment] 2016-10-10 23:52
tentatively closing. feel free to reopen!

**Closed** 2016-10-10 23:52 UTC
